### ISSUE TITLE
[Facing a problem]

### ISSUE THREAD

**Issue by niloy37** [danielkrupinski/Inflame#3]
Cannot find the Inflame.sln  after I used gitbash to clone it. and also the previous issue as stated how to change it to manual map?

**Comment by danielkrupinski** [comment]
`git checkout manual-map` 
If you are facing any problems, you can download binaries from releases section.

**Comment by niloy37** [comment]
I used Inflame64 and build it using release x64 
and when i kept it in same directory it saied this error
img - https://imgur.com/a/EF8kRHj
and Also I didnt understand where to use this example command
Inflame64 -manual-map test64.dll 2048 should I do it in cmd?
(Edit 1)
This is how it looks -
![image](https://user-images.githubusercontent.com/43872939/57096437-138ac080-6d37-11e9-8555-141399c4871a.png)
(Edit 2)
With Cmd it shows this error
![image](https://user-images.githubusercontent.com/43872939/57096576-72503a00-6d37-11e9-80a8-df2a35263142.png)

**Comment by danielkrupinski** [comment]
Error message clearly states the program could not locate Inflame64.dll required by 64-bit version of injector. Build project from `manual-map` branch and rename resulting .dll file to *Inflame64.dll*

**Comment by niloy37** [comment]
Fixed Thanks!
